In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('Bank_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
#Drop irrelevant columns

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
label=LabelEncoder()

data['Gender']=label.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [5]:
data.tail()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
onehot=OneHotEncoder()
onehot_geo=onehot.fit_transform(data[['Geography']]).toarray()
onehot_geo

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
onehot.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
onehot_geo_df=pd.DataFrame(onehot_geo,columns=onehot.get_feature_names_out(['Geography']))
onehot_geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
data=pd.concat([data.drop(['Geography'],axis=1),onehot_geo_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
# Save the enoders and scaler models into a pickle files

with open("label_encoder_gender.pkl","wb") as file:
    pickle.dump(label,file)
    
with open("onehot_encoder_geo.pkl","wb") as file:
    pickle.dump(onehot,file)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
X=data.drop(['Exited'],axis=1)
y=data['Exited']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [14]:
X_train.shape

(8000, 12)

In [15]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [16]:
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

In [17]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

## ANN Model Implementation

In [18]:
import tensorflow as tf

2026-09-01 22:07:12.755748: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-09-01 22:07:12.830174: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-09-01 22:07:12.830230: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-09-01 22:07:12.832013: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-09-01 22:07:12.842398: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-09-01 22:07:12.843297: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-09-01 22:07:14.724506: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [20]:
X_train.shape

(8000, 12)

In [21]:
(X_train.shape[1],)

(12,)

In [22]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),    # HL1
    Dense(32,activation='relu'),                                    #HL2
    Dense(1,activation='sigmoid')                                   #output layer
])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [24]:
import tensorflow

opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

loss

In [25]:
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [26]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="log/fit/"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [27]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [28]:
import tensorflow as tf
import keras
print(tf.__version__)
print(keras.__version__)

2.15.0
2.15.0

In [29]:
model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 4s 9ms/step - loss: 0.4030 - accuracy: 0.8354 - val_loss: 0.3645 - val_accuracy: 0.8495
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3561 - accuracy: 0.8539 - val_loss: 0.3630 - val_accuracy: 0.8540
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3468 - accuracy: 0.8556 - val_loss: 0.3550 - val_accuracy: 0.8595
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3425 - accuracy: 0.8608 - val_loss: 0.3459 - val_accuracy: 0.8595
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3416 - accuracy: 0.8580 - val_loss: 0.3434 - val_accuracy: 0.8570
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3386 - accuracy: 0.8629 - val_loss: 0.3422 - val_accuracy: 0.8585
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3345 - accuracy: 0.8621 - val_loss: 0.3533 - val_accuracy: 0.8525
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3338 - accuracy: 0.8609 - val_loss: 0.3677 - val_accuracy: 0.8585
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3330 - accuracy: 0.8631 - val_loss: 0.3409 - val_accuracy: 0.8610
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3301 - accuracy: 0.8602 - val_loss: 0.3395 - val_accuracy: 0.8650
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3284 - accuracy: 0.8629 - val_loss: 0.3802 - val_accuracy: 0.8540
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3270 - accuracy: 0.8649 - val_loss: 0.3574 - val_accuracy: 0.8595
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3246 - accuracy: 0.8658 - val_loss: 0.3410 - val_accuracy: 0.8625
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3226 - accuracy: 0.8690 - val_loss: 0.3541 - val_accuracy: 0.8605
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3174 - accuracy: 0.8661 - val_loss: 0.3473 - val_accuracy: 0.8565
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3188 - accuracy: 0.8662 - val_loss: 0.3573 - val_accuracy: 0.8610
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3127 - accuracy: 0.8686 - val_loss: 0.3657 - val_accuracy: 0.8635
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3098 - accuracy: 0.8726 - val_loss: 0.3515 - val_accuracy: 0.8625
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3073 - accuracy: 0.8702 - val_loss: 0.3599 - val_accuracy: 0.8555
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3074 - accuracy: 0.8710 - val_loss: 0.3595 - val_accuracy: 0.8575

In [30]:
model.save('model.h5')

/home/bhargav/Desktop/Python/Machine_learning/Deep Learning/ANN Project/venv/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [31]:
#Load tensorboard extension

%load_ext tensorboard