### Importting the car_dheko dataset

In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("car_dheko.csv",index_col=0) #To remove the unnamed index column
#or use df.drop('Unnamed:0',axis=1,inplace=True)

In [3]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.drop(columns=['car_name','brand'],inplace=True)

In [5]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [6]:
#Check any null values
df.isnull().sum()

model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [7]:
df['model'].unique()        #returns all values excatly once

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [8]:
num_features=[features for features in df.columns if df[features].dtype != 'O']
print("no.of  numerical features",len(num_features))
cat_features=[features for features in df.columns if df[features].dtype=='O']
print("no.of categorical features",len(cat_features))

no.of  numerical features 7
no.of categorical features 4

In [9]:
df.shape

(15411, 11)

In [10]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [11]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [12]:
from sklearn.model_selection import train_test_split
X=df.drop('selling_price',axis=1)
y=df['selling_price']

In [13]:
X

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [14]:
X['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [15]:
len(X['model'].unique())

120

### Label encoding for the caregorical value

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [17]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [18]:
num_features=X.select_dtypes(exclude='object').columns
onehot_features=['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

num_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessor=ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,onehot_features),
        ('StandardScaler',num_transformer,num_features)
    ],remainder='passthrough'
)

In [19]:
X=preprocessor.fit_transform(X)

In [20]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
X_train.shape,X_test.shape

((10787, 14), (4624, 14))

In [22]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  0.02291783,
        -0.27665384, -0.40302241],
       [ 1.        ,  0.        ,  1.        , ..., -0.17282578,
        -0.2759557 , -0.40302241],
       [ 1.        ,  0.        ,  1.        , ..., -0.0480872 ,
        -0.39068268, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]], shape=(10787, 14))

In [23]:
y_train

8218     630000
13969    550000
16328    415000
11684    450000
7453     740000
          ...
6581     665000
17029    249000
6839     250000
1104     620000
9295     960000
Name: selling_price, Length: 10787, dtype: int64

In [24]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [25]:
def evaluate(true,predicted):
    mae=mean_squared_error(true,predicted)
    mse=mean_absolute_error(true,predicted)
    r2=r2_score(true,predicted)
    rmse=np.sqrt(mse)
    
    return mae,rmse,r2

### ThereFore KneighnorRegressor and DecisiontreeRegressor performed well

In [28]:
models={
    'Linear Regression':LinearRegression(),
    'Ridge Regression':Ridge(),
    'Lasso Regression':Lasso(),
    'KN Regression':KNeighborsRegressor(),
    'Decision Tree Regression':DecisionTreeRegressor(),
    'AdaBoost REgression':AdaBoostRegressor(),
    'GradientBoost Regression':GradientBoostingRegressor()
}



for i in range (len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)  #Train the model
    
    #Predict Train and Test data
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    
    model_train_mae,model_train_rmse,model_train_r2=evaluate(y_train,y_train_pred)
    
    model_test_mae,model_test_rmse,model_test_r2=evaluate(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    
    print("Model Performance on Training data")
    
    print("-mae {:.4f}".format(model_train_mae))
    print("-rmse {:.4f}".format(model_train_rmse))
    print("-r2 {:.4f}".format(model_train_r2))
    
    print("-"*35)
    
    print("Model performance on test data")
    
    print("-mae :{:.4f}".format(model_test_mae))
    print("-rmse :{:.4f}".format(model_test_rmse))
    print("r2 :{:.4f}".format(model_test_r2))
    
    print("="*35)
    print("\n")

Linear Regression
Model Performance on Training data
-mae 312831831093.0353
-rmse 518.1097
-r2 0.6183
-----------------------------------
Model performance on test data
-mae :257613903997.1092
-rmse :530.4054
r2 :0.6575
===================================


Ridge Regression
Model Performance on Training data
-mae 312832747644.5701
-rmse 518.0668
-r2 0.6183
-----------------------------------
Model performance on test data
-mae :257596266396.6422
-rmse :530.3554
r2 :0.6575
===================================


Lasso Regression
Model Performance on Training data
-mae 312831842666.6471
-rmse 518.1087
-r2 0.6183
-----------------------------------
Model performance on test data
-mae :257612992800.0465
-rmse :530.4049
r2 :0.6575
===================================


KN Regression
Model Performance on Training data
-mae 114344591063.3170
-rmse 303.0357
-r2 0.8605
-----------------------------------
Model performance on test data
-mae :82886297633.1369
-rmse :341.6951
r2 :0.8898
===================================


Decision Tree Regression
Model Performance on Training data
-mae 413298475.0162
-rmse 68.7669
-r2 0.9995
-----------------------------------
Model performance on test data
-mae :83309384507.6563
-rmse :356.2969
r2 :0.8892
===================================


AdaBoost REgression
Model Performance on Training data
-mae 193397006415.1595
-rmse 588.6540
-r2 0.7640
-----------------------------------
Model performance on test data
-mae :264381670555.6810
-rmse :608.0790
r2 :0.6485
===================================


GradientBoost Regression
Model Performance on Training data
-mae 38668498615.2869
-rmse 331.8296
-r2 0.9528
-----------------------------------
Model performance on test data
-mae :77924178667.5492
-rmse :359.5996
r2 :0.8964
===================================

### GradientBoost Regression is best for regression problems

### Parameter Tuning

In [29]:
models={
    'Random Forest Regressor':RandomForestRegressor(n_estimators=100, min_samples_split=2, max_features='log2',
                                                    max_depth=None, n_jobs=-1),
    'KNeighbor Regressor':KNeighborsRegressor(n_neighbors=10,n_jobs=-1),
    'GradientBoost Regressor':GradientBoostingRegressor(
        n_estimators=200,min_samples_split=8,max_depth=10,loss='huber',criterion='squared_error'
    )

}


for i in range (len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)  #Train the model
    
    #Predict Train and Test data
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    
    model_train_mae,model_train_rmse,model_train_r2=evaluate(y_train,y_train_pred)
    
    model_test_mae,model_test_rmse,model_test_r2=evaluate(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    
    print("Model Performance on Training data")
    
    print("-mae {:.4f}".format(model_train_mae))
    print("-rmse {:.4f}".format(model_train_rmse))
    print("-r2 {:.4f}".format(model_train_r2))
    
    print("-"*35)
    
    print("Model performance on test data")
    
    print("-mae :{:.4f}".format(model_test_mae))
    print("-rmse :{:.4f}".format(model_test_rmse))
    print("r2 :{:.4f}".format(model_test_r2))
    
    print("="*35)
    print("\n")

Random Forest Regressor
Model Performance on Training data
-mae 17508150263.5312
-rmse 200.3202
-r2 0.9786
-----------------------------------
Model performance on test data
-mae :52420363986.4893
-rmse :318.7671
r2 :0.9303
===================================


KNeighbor Regressor
Model Performance on Training data
-mae 139705960442.1989
-rmse 322.5508
-r2 0.8295
-----------------------------------
Model performance on test data
-mae :88720468069.9881
-rmse :348.2563
r2 :0.8820
===================================


GradientBoost Regressor
Model Performance on Training data
-mae 3867171355.4872
-rmse 190.6041
-r2 0.9953
-----------------------------------
Model performance on test data
-mae :56130468927.8116
-rmse :316.5593
r2 :0.9254
===================================